version: '3'

services:
  traefik:
    image: traefik:v2.0
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/traefik

  whoami:
    image: containous/whoami

  nginx:
    image: nginx:alpine

  dumper:
    build:
      context: dumper