[http.routers]
  [http.routers.nginx]
    rule = "Host(`nginx`)"
    service = "nginx"

[http.services]
  [http.services.nginx]
    [http.services.nginx.loadBalancer]
      [[http.services.nginx.loadBalancer.servers]]
        url = "http://traefik-playground_nginx_1"
      [[http.services.nginx.loadBalancer.servers]]
        url = "http://traefik-playground_nginx_2"
      [[http.services.nginx.loadBalancer.servers]]
        url = "http://traefik-playground_nginx_3"
      [[http.services.nginx.loadBalancer.servers]]
        url = "http://traefik-playground_nginx_4"
      [[http.services.nginx.loadBalancer.servers]]
        url = "http://traefik-playground_nginx_5"
      [[http.services.nginx.loadBalancer.servers]]
        url = "http://traefik-playground_nginx_6"
      [[http.services.nginx.loadBalancer.servers]]
        url = "http://traefik-playground_nginx_7"
      [[http.services.nginx.loadBalancer.servers]]
        url = "http://traefik-playground_nginx_8"
      [[http.services.nginx.loadBalancer.servers]]
        url = "http://traefik-playground_nginx_9"
      [[http.services.nginx.loadBalancer.servers]]
        url = "http://traefik-playground_nginx_10"
